### ISSUE TITLE
Voice functions cannot be bound to mouse buttons.

### ISSUE THREAD

**Issue by bradley-r** [KorbsStudio/Guilded-for-Linux#3]
When attempting to bind mouse buttons (in this case 8 and 9 but it's the same for all), the capture field changes to blank (presumably meaning the input is detected) instead of the specified input; this empty state is just that however, as after exiting settings no keybind is set - see image below. This occurs both in this app and the web-app, but Discord and other native apps have no trouble using the mouse buttons. 

![Screenshot_20200628_140134](https://user-images.githubusercontent.com/43189454/85948276-f0ae6900-b947-11ea-95de-7bf844634dac.png)

In both the web app and this app, mouse buttons 8 and 9 execute their functions (forward and back) instead of being captured, leading me to believe it may be a limitation only addressable by a truly native version. Interestingly, any mouse button activates the 'record' button - mouse 1 and 2 as expected, but also any others.

I'm on Fedora so if this works on your Ubuntu-based systems I'll assume it's relying on distro-specific files to allow for mouse button capture, but, even if so, at least you are aware of the issue.

**Comment by KorbsStudio** [comment]
The app by default uses button 8 and 9 has foward and back and Linux. Same goes for Discord.

**Comment by bradley-r** [comment]
Yep, that part works fine in both - it's just that mouse buttons cannot be assigned actions within Guilded; in Discord and in-game communications, I bind PTT to my mouse for easy access, and any mouse button used when recording the keybind in the app is not set as a hotkey as I'd like it to be. It's not a huge problem of course - voice activation is somewhat of an alternative - but if the functionality is available I'd be grateful if it was added at some point.

**Comment by KorbsStudio** [comment]
Due to some limitations, using voice channels on Guilded will not work on this port to Linux.
