### ISSUE TITLE
Cannot join voice chats

### ISSUE THREAD

**Issue by TheGag96** [KorbsStudio/Guilded-for-Linux#4]
Attempting to join a voice chat on elementary OS 5.1.5 w/ kernel 5.6.14 fails and yields two toast notifications ("Device not supported" and "rtpCapabilities is required"). Joining voice chat on web (Firefox) works fine.

Any help? Thanks!

**Comment by KorbsStudio** [comment]
This is due to limitations. DiscordRTP does not work in this port to Linux.
