### ISSUE TITLE
Guilded Issue

### ISSUE THREAD

**Issue by iP2-Rune** [KorbsStudio/Guilded-for-Linux#5]
Hey i followed all the correct directions to install the unofficial guilded software but for some reason it will ask me 
![Screenshot_2020-10-08_23-25-16](https://user-images.githubusercontent.com/71159101/95543356-e62b5300-09bd-11eb-90bb-63f250bf9563.png) ill say yes and it will say done and ill try to execute it and it doesnt open? am I missing something or doing something wrong? 

ps. I'm also running Debian Buster 10 if that helps?

**Comment by KorbsStudio** [comment]
Please use the official Guilded client, as it's now available for Linux!
